import XCTest
@testable import XCTriageKit

final class GitHubPRWriterTests: XCTestCase {

    // Records every shelled-out command instead of running it, so these
    // tests never invoke real git/gh or touch the network. Same isolation
    // goal as SandboxValidatorTests' fake tool scripts, different mechanism:
    // GitHubPRWriter takes an injectable CommandRunner closure instead of
    // shelling to a script on disk.
    private final class RecordingRunner: @unchecked Sendable {
        struct Call: Equatable { let executable: String; let arguments: [String]; let cwd: String }
        private(set) var calls: [Call] = []
        var exitCode: Int32 = 0
        var prCreateOutput: String = "https://github.com/example/example/pull/42\n"

        func run(_ executable: String, _ arguments: [String], _ cwd: String) async throws -> (Int32, String) {
            calls.append(Call(executable: executable, arguments: arguments, cwd: cwd))
            if arguments.first == "pr" {
                return (exitCode, prCreateOutput)
            }
            return (exitCode, "")
        }
    }

    private func site() -> FailureSite {
        FailureSite(file: "Sources/Foo.swift", line: 10, column: nil, testName: "FooTests.test_a", errorMessage: "unresolved identifier 'Bar'")
    }

    private func fingerprint() -> FailureFingerprint {
        FailureFingerprint(category: .compilationError, failureSites: [site()])
    }

    private func proposal(rationale: String = "Bar was renamed to Baz upstream") -> PatchProposal {
        PatchProposal(filePath: "Sources/Foo.swift", unifiedDiff: "--- a/Sources/Foo.swift\n+++ b/Sources/Foo.swift\n", rationale: rationale, confidence: 0.82)
    }

    private func sandboxResult() -> SandboxValidator.Result {
        SandboxValidator.Result(applied: true, buildSucceeded: true, testSucceeded: true, output: "")
    }

    private func makeWriter(_ runner: RecordingRunner) -> GitHubPRWriter {
        GitHubPRWriter(runCommand: runner.run)
    }

    // MARK: - createDraftPR

    func test_createDraftPR_usesFingerprintedBranchName() async throws {
        let runner = RecordingRunner()
        let writer = makeWriter(runner)

        let result = try await writer.createDraftPR(
            proposal: proposal(), fingerprint: fingerprint(), category: .compilationError,
            failureSite: site(), sandboxResult: sandboxResult(), repoRoot: "/tmp/repo"
        )

        let expectedBranch = "xctriage/remediate-\(fingerprint().value)"
        XCTAssertEqual(result.branchName, expectedBranch)
        XCTAssertTrue(runner.calls.contains { $0.arguments == ["checkout", "-b", expectedBranch] })
    }

    func test_createDraftPR_commitMessageHasNoAIAttributionAndIncludesFingerprint() async throws {
        let runner = RecordingRunner()
        let writer = makeWriter(runner)

        _ = try await writer.createDraftPR(
            proposal: proposal(), fingerprint: fingerprint(), category: .compilationError,
            failureSite: site(), sandboxResult: sandboxResult(), repoRoot: "/tmp/repo"
        )

        let commitCall = runner.calls.first { $0.arguments.first == "commit" }
        XCTAssertNotNil(commitCall)
        let message = commitCall?.arguments.last ?? ""
        XCTAssertFalse(message.lowercased().contains("generated by"))
        XCTAssertFalse(message.lowercased().contains("claude"))
        XCTAssertFalse(message.lowercased().contains(" ai "))
        XCTAssertTrue(message.contains(fingerprint().value))
    }

    func test_createDraftPR_pushesBranchBeforeOpeningPR() async throws {
        let runner = RecordingRunner()
        let writer = makeWriter(runner)

        let result = try await writer.createDraftPR(
            proposal: proposal(), fingerprint: fingerprint(), category: .compilationError,
            failureSite: site(), sandboxResult: sandboxResult(), repoRoot: "/tmp/repo"
        )

        let pushIndex = runner.calls.firstIndex { $0.arguments.first == "push" }
        let prIndex = runner.calls.firstIndex { $0.arguments.first == "pr" }
        XCTAssertNotNil(pushIndex)
        XCTAssertNotNil(prIndex)
        XCTAssertLessThan(pushIndex!, prIndex!)
        XCTAssertTrue(runner.calls[pushIndex!].arguments.contains(result.branchName))
    }

    func test_createDraftPR_opensAsDraftAgainstRequestedBaseBranch() async throws {
        let runner = RecordingRunner()
        let writer = makeWriter(runner)

        _ = try await writer.createDraftPR(
            proposal: proposal(), fingerprint: fingerprint(), category: .compilationError,
            failureSite: site(), sandboxResult: sandboxResult(), repoRoot: "/tmp/repo", baseBranch: "main"
        )

        let prCall = runner.calls.first { $0.executable.hasSuffix("gh") }
        XCTAssertNotNil(prCall)
        XCTAssertTrue(prCall?.arguments.contains("--draft") ?? false)
        XCTAssertTrue(prCall?.arguments.contains("main") ?? false)
    }

    func test_createDraftPR_returnsPRURLFromGhOutput() async throws {
        let runner = RecordingRunner()
        let writer = makeWriter(runner)

        let result = try await writer.createDraftPR(
            proposal: proposal(), fingerprint: fingerprint(), category: .compilationError,
            failureSite: site(), sandboxResult: sandboxResult(), repoRoot: "/tmp/repo"
        )

        XCTAssertEqual(result.prURL, "https://github.com/example/example/pull/42")
    }

    func test_createDraftPR_throwsWhenAGitStepFails() async {
        let runner = RecordingRunner()
        runner.exitCode = 1
        let writer = makeWriter(runner)

        do {
            _ = try await writer.createDraftPR(
                proposal: proposal(), fingerprint: fingerprint(), category: .compilationError,
                failureSite: site(), sandboxResult: sandboxResult(), repoRoot: "/tmp/repo"
            )
            XCTFail("expected failure")
        } catch TriageError.remediationCommandFailed {
            // expected
        } catch {
            XCTFail("expected TriageError.remediationCommandFailed, got \(error)")
        }
    }

    // MARK: - PR body shape (pure, no runner needed)

    func test_prBody_containsRequiredSectionsAndNoAIAttribution() {
        let body = GitHubPRWriter.prBody(
            fingerprint: fingerprint(), category: .compilationError, failureSite: site(),
            proposal: proposal(), sandboxResult: sandboxResult()
        )

        for heading in ["## Summary", "## Failure", "## Root Cause", "## Change", "## Validation", "## Risk", "## Rollback"] {
            XCTAssertTrue(body.contains(heading), "missing \(heading)")
        }
        XCTAssertFalse(body.lowercased().contains("generated by"))
        XCTAssertFalse(body.lowercased().contains("claude"))
        XCTAssertFalse(body.contains("Jira"))
        XCTAssertFalse(body.contains("Incident"))
    }

    func test_prBody_omitsRootCauseSectionWhenRationaleEmpty() {
        let body = GitHubPRWriter.prBody(
            fingerprint: fingerprint(), category: .compilationError, failureSite: site(),
            proposal: proposal(rationale: ""), sandboxResult: sandboxResult()
        )
        XCTAssertFalse(body.contains("## Root Cause"))
    }

    func test_prBody_reportsSandboxOutcome() {
        let failedSandbox = SandboxValidator.Result(applied: true, buildSucceeded: true, testSucceeded: false, output: "")
        let body = GitHubPRWriter.prBody(
            fingerprint: fingerprint(), category: .compilationError, failureSite: site(),
            proposal: proposal(), sandboxResult: failedSandbox
        )
        XCTAssertTrue(body.contains("passed"))
        XCTAssertTrue(body.contains("failed"))
    }

    // MARK: - Branch/commit naming (pure)

    func test_branchName_isNamespacedAndFingerprinted() {
        let name = GitHubPRWriter.branchName(fingerprint: fingerprint())
        XCTAssertEqual(name, "xctriage/remediate-\(fingerprint().value)")
    }
}
