import Foundation

// Same pipe-draining rationale as XCResultParser/SandboxValidator:
// readabilityHandler drains continuously so a chatty `gh pr create` can't
// fill the pipe's kernel buffer and deadlock the child against the parent's
// termination wait.
private final class PRWriterOutputBuffer: @unchecked Sendable {
    var data = Data()
}

// Turns a sandbox-validated PatchProposal into a real GitHub pull request:
// branch, commit, push, `gh pr create --draft`. Always opens as a draft —
// this is the ceiling of autonomy level 2 in docs/architecture (PART_B,
// sections 38/104): a human must review and merge, this type has no merge
// capability at all, by design. Never touches the caller's main branch
// directly and never invokes `gh pr merge` anywhere in this file.
//
// Shell-outs go through an injectable CommandRunner closure (default: real
// Process) so unit tests can verify branch naming, commit message shape,
// and PR body shape without ever invoking git/gh or touching the network.
public struct GitHubPRWriter: Sendable {

    public struct Result: Sendable, Equatable {
        public let branchName: String
        public let prURL: String?
        public let output: String
    }

    public typealias CommandRunner = @Sendable (
        _ executable: String, _ arguments: [String], _ cwd: String
    ) async throws -> (Int32, String)

    private let gitPath: String
    private let ghPath: String
    private let runCommand: CommandRunner

    public init(
        gitPath: String = "/usr/bin/git",
        ghPath: String = "/usr/bin/gh",
        runCommand: CommandRunner? = nil
    ) {
        self.gitPath = gitPath
        self.ghPath = ghPath
        self.runCommand = runCommand ?? Self.runProcess
    }

    // repoRoot is the real checkout (already at the commit the failure was
    // observed on) — not a throwaway sandbox worktree, that validation
    // already happened separately via SandboxValidator before this is ever
    // called. Callers must only call this after policy allow + a passing
    // sandbox result; this type does not re-check either gate itself.
    public func createDraftPR(
        proposal: PatchProposal,
        fingerprint: FailureFingerprint,
        category: FailureCategory,
        failureSite: FailureSite,
        sandboxResult: SandboxValidator.Result,
        repoRoot: String,
        baseBranch: String = "main"
    ) async throws -> Result {
        let branch = Self.branchName(fingerprint: fingerprint)
        var combinedOutput = ""

        func exec(_ executable: String, _ arguments: [String]) async throws -> String {
            let (code, out) = try await runCommand(executable, arguments, repoRoot)
            combinedOutput += out
            guard code == 0 else {
                throw TriageError.remediationCommandFailed(
                    "\(executable) \(arguments.joined(separator: " "))", out
                )
            }
            return out
        }

        _ = try await exec(gitPath, ["checkout", "-b", branch])

        let diffPath = NSTemporaryDirectory() + "xctriage-pr-\(UUID().uuidString).diff"
        try proposal.unifiedDiff.write(toFile: diffPath, atomically: true, encoding: .utf8)

        _ = try await exec(gitPath, ["apply", diffPath])
        _ = try await exec(gitPath, ["add", proposal.filePath])
        _ = try await exec(gitPath, ["commit", "-m", Self.commitMessage(category: category, fingerprint: fingerprint)])
        _ = try await exec(gitPath, ["push", "-u", "origin", branch])

        let prOut = try await exec(ghPath, [
            "pr", "create",
            "--draft",
            "--base", baseBranch,
            "--head", branch,
            "--title", Self.prTitle(category: category, proposal: proposal),
            "--body", Self.prBody(
                fingerprint: fingerprint, category: category, failureSite: failureSite,
                proposal: proposal, sandboxResult: sandboxResult
            ),
        ])

        let url = prOut.trimmingCharacters(in: .whitespacesAndNewlines)
        return Result(branchName: branch, prURL: url.isEmpty ? nil : url, output: combinedOutput)
    }

    // MARK: - Pure helpers (no shell-out, directly unit-testable)

    public static func branchName(fingerprint: FailureFingerprint) -> String {
        "xctriage/remediate-\(fingerprint.value)"
    }

    // Plain, imperative, no AI attribution — matches the rest of this repo's
    // commit message style and the hard rule against "Generated by"/model
    // markers in anything this tool writes to a target repo.
    public static func commitMessage(category: FailureCategory, fingerprint: FailureFingerprint) -> String {
        "Fix \(category.rawValue) [\(fingerprint.value)]"
    }

    public static func prTitle(category: FailureCategory, proposal: PatchProposal) -> String {
        "Fix \(category.rawValue): \((proposal.filePath as NSString).lastPathComponent)"
    }

    // Structured template per docs/architecture PART_B section 104: Summary /
    // Failure / Root Cause / Change / Validation / Risk / Rollback. Fields
    // with no real backing data (e.g. Related Incident/Jira — nothing in
    // this pipeline produces those) are left out entirely rather than
    // invented.
    public static func prBody(
        fingerprint: FailureFingerprint,
        category: FailureCategory,
        failureSite: FailureSite,
        proposal: PatchProposal,
        sandboxResult: SandboxValidator.Result
    ) -> String {
        var sections: [String] = []

        sections.append(
            "## Summary\nAutomated single-file fix for a \(category.displayName.lowercased()) failure (fingerprint `\(fingerprint.value)`)."
        )

        var failureLines = ["## Failure"]
        if let testName = failureSite.testName {
            failureLines.append("Test: `\(testName)`")
        }
        if let file = failureSite.file {
            let loc = failureSite.line.map { ":\($0)" } ?? ""
            failureLines.append("File: `\(file)\(loc)`")
        }
        failureLines.append("Error: \(failureSite.errorMessage)")
        sections.append(failureLines.joined(separator: "\n"))

        if !proposal.rationale.isEmpty {
            sections.append("## Root Cause\n\(proposal.rationale)")
        }

        sections.append("## Change\nModifies `\(proposal.filePath)`. See the diff in this PR for the exact change.")

        sections.append("""
        ## Validation
        - Sandbox build: \(sandboxResult.buildSucceeded ? "passed" : "failed")
        - Sandbox test (\(failureSite.testName ?? "target test")): \(sandboxResult.testSucceeded ? "passed" : "failed")
        """)

        sections.append(
            "## Risk\nSingle-file change. Patch confidence \(String(format: "%.2f", proposal.confidence)). Passed the RemediationPolicy gate before this PR was opened."
        )

        sections.append(
            "## Rollback\nClose this PR and delete branch `\(branchName(fingerprint: fingerprint))`, or revert after merge."
        )

        return sections.joined(separator: "\n\n")
    }

    // MARK: - Default runner

    private static func runProcess(_ executable: String, _ arguments: [String], _ cwd: String) async throws -> (Int32, String) {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = arguments
        process.currentDirectoryURL = URL(fileURLWithPath: cwd)

        let stdoutPipe = Pipe()
        let stderrPipe = Pipe()
        process.standardOutput = stdoutPipe
        process.standardError = stderrPipe

        return try await withCheckedThrowingContinuation { continuation in
            let outHandle = stdoutPipe.fileHandleForReading
            let errHandle = stderrPipe.fileHandleForReading
            let bufferQueue = DispatchQueue(label: "xctriage.prwriter.output")
            let stdoutBuffer = PRWriterOutputBuffer()
            let stderrBuffer = PRWriterOutputBuffer()

            outHandle.readabilityHandler = { handle in
                let chunk = handle.availableData
                guard !chunk.isEmpty else { return }
                bufferQueue.sync { stdoutBuffer.data.append(chunk) }
            }
            errHandle.readabilityHandler = { handle in
                let chunk = handle.availableData
                guard !chunk.isEmpty else { return }
                bufferQueue.sync { stderrBuffer.data.append(chunk) }
            }

            process.terminationHandler = { p in
                let trailingOut = outHandle.readDataToEndOfFile()
                let trailingErr = errHandle.readDataToEndOfFile()
                outHandle.readabilityHandler = nil
                errHandle.readabilityHandler = nil

                let combined: String = bufferQueue.sync {
                    stdoutBuffer.data.append(trailingOut)
                    stderrBuffer.data.append(trailingErr)
                    let out = String(data: stdoutBuffer.data, encoding: .utf8) ?? ""
                    let err = String(data: stderrBuffer.data, encoding: .utf8) ?? ""
                    return err.isEmpty ? out : out + "\n" + err
                }
                continuation.resume(returning: (p.terminationStatus, combined))
            }
            do {
                try process.run()
            } catch {
                continuation.resume(throwing: error)
            }
        }
    }
}
